import Link from "next/link";
import { Evidence } from "./evidence";
export { Evidence } from "./evidence";
import type { ReactNode } from "react";
import type { DashboardModel } from "@/application/dashboard/model";
import type { Decision } from "@/domain/decision/engine";
import type { ReviewArtifact, AllocationProposal } from "@/domain/workflow/contracts";
import type { Ranking } from "@/domain/ranking/rank";
export const navigation = [
  { group: "Overview", items: [["dashboard", "Dashboard"], ["holdings", "Holdings"], ["risk", "Risk"], ["performance", "Performance"]] },
  { group: "Research & Decisions", items: [["vn30", "VN30 Universe"], ["ranking", "Scoring & Ranking"], ["decisions", "Decision Center"], ["dca", "DCA Planner"]] },
  { group: "Operations", items: [["transactions", "Transactions"], ["reviews", "Reviews"], ["journal", "Journal"]] },
  { group: "Data", items: [["imports", "Imports"], ["data", "Data Freshness"], ["audit", "Audit / Methodology"]] },
  { group: "Settings", items: [["settings", "Settings"]] },
];
const titles: Record<string, string> = Object.fromEntries(navigation.flatMap(g => g.items));
export function Status({ children }: { children: ReactNode }) { return <span className="status">{children}</span>; }
export function Panel({ title, children }: { title: string; children: ReactNode }) { return <section aria-label={title}><h2>{title}</h2>{children}</section>; }
export function Metrics({ values }: { values: Record<string, unknown> }) { return <dl className="metrics">{Object.entries(values).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value == null ? "Unavailable" : String(value)}</dd></div>)}</dl>; }
export function Table({ headers, rows, empty = "No records available." }: { headers: string[]; rows: ReactNode[][]; empty?: string }) {
  return rows.length ? <div className="table-scroll" role="region" aria-label={headers.join(", ")} tabIndex={0}><table><thead><tr>{headers.map(h => <th scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell ?? "Unavailable"}</td>)}</tr>)}</tbody></table></div> : <p className="empty">{empty}</p>;
}
const href = (route: string, id: string) => `/${route}/${encodeURIComponent(id)}`;
function Ref({ route, id }: { route: string; id: string | null | undefined }) { return id ? <Link href={href(route, id)}>{id}</Link> : <>Unavailable</>; }
export function DecisionView({ decision: d }: { decision: Decision }) {
  return <><Panel title={`${d.ticker} · Economic Decision State`}><Status>{d.decisionState}</Status><p>Execution Status: <strong>{d.executionStatus}</strong></p><p>Review Status: <strong>{d.reviewStatus}</strong> · {d.tradeAuthorization}</p><p>{d.suggestedAction}</p><Metrics values={{ "Data as-of": d.asOf, "Evidence cutoff": d.lineage.evidenceCutoff, "Portfolio snapshot": d.lineage.snapshotId, "Methodology": d.methodology, "Scope": d.scope }} /><p className="notice">Historical as-calculated artifact. Current freshness and actionability require server revalidation. This screen does not authorize a new trade.</p></Panel><Panel title="Why this state?"><ul>{d.reasons.map(r => <li key={r}>{r}</li>)}</ul><p>Score reference: <Ref route="scoring" id={d.lineage.scorecardId} /> · Ranking: <Ref route="ranking" id={d.lineage.rankingId} /></p><p>Prior decision: <Ref route="decisions" id={d.priorDecisionId} /></p><Evidence value={{ thesis: d.input.assessment.thesis, keyPositives: d.input.assessment.keyPositives, keyRisks: d.input.assessment.keyRisks, invalidationConditions: d.input.assessment.invalidationConditions, valuation: d.input.assessment.valuation, requiredReturn: d.requiredReturn, residualRisk: d.input.assessment.risk, portfolioImpact: d.portfolioImpact, opportunityCost: d.opportunityCost, missingEvidence: d.missingEvidence }} /></Panel><Panel title="Evidence & lineage"><Evidence value={{ lineage: d.lineage, evidence: d.input.evidence, assessment: d.input.assessment }} /></Panel></>;
}
export function RankingView({ ranking: r }: { ranking: Ranking }) {
  return <Panel title="Formal ranking / Top 10"><p className="notice">Top 10 ≠ Buy list. Rank #1 alone provides no purchase authorization.</p><Metrics values={{ Status: r.status, "Data as-of": r.asOf, Methodology: r.methodology, "Reference version": r.input.universe.referenceVersion }} /><Table headers={["Rank", "Security", "Score", "Top-10 eligibility", "Confidence", "Data quality", "Near-tie cluster"]} rows={r.entries.map(e => { const c = r.input.cards.find(c => c.id === e.scorecardId); return [e.displayRank, <Ref key={e.securityId} route="scoring" id={e.scorecardId} />, e.score, r.top10.some(t => t.securityId === e.securityId) ? "Selected by M6.4" : "Outside Top 10", c?.confidence, c?.dataQuality, e.cluster]; })} /><h3>Structured exclusion reasons</h3><Table headers={["Excluded security", "Score", "Reason code", "Detail", "Evidence reference"]} rows={r.excluded.flatMap(e => e.reasons.map(reason => [e.securityId, e.score, reason.code, reason.detail, reason.evidenceReference]))} /><h3>Near-tie information</h3><Table headers={["Anchor score", "Securities", "Return tie-break used", "Display-only ties"]} rows={r.clusters.map(c => [c.anchor, c.securityIds.join(", "), String(c.returnTieBreakUsed), c.displayOnlyTies.map(t => t.join(", ")).join(" · ") || "None"])} /></Panel>;
}
export function ProposalView({ proposal: p }: { proposal: AllocationProposal }) {
  return <><Panel title="Allocation proposal"><p className="notice">Proposal ≠ Executed Transaction. This proposal remains a historical plan; execution is evidenced only by confirmed ledger transactions.</p><Status>{p.outcome}</Status>{p.outcome === "HOLD CASH" && <p>No qualified capital-allocation opportunity. Holding cash is valid.</p>}<Metrics values={{ "Ledger cash (VND)": p.ledgerCash, "Available capital (VND)": p.availableCapital, "Reserved cash (VND)": p.reservedCash, "Monthly contribution (already included in cash)": p.newMonthlyContribution, "Proposed allocation (VND)": p.proposedAllocation, "Residual / unallocated cash (VND)": p.unallocatedCash, "Portfolio as-of": p.portfolioAsOf, "Evidence cutoff": p.evidenceCutoff, "Data quality": p.dataQuality }} /><p>Review: <Ref route="reviews" id={p.reviewId} /> · Snapshot: <Ref route="audit" id={p.portfolioSnapshotReference} /></p><h3>Candidate decisions</h3><Table headers={["Decision", "Economic state", "Execution status", "Economic priority", "Reasons"]} rows={p.candidates.map(c => [<Ref key={c.decisionId} route="decisions" id={c.decisionId} />, c.decisionState, c.executionStatus, c.economicPriority, c.reasons.join(" · ")])} /><h3>Proposed lots</h3><Evidence value={p.items} /><h3>Risk, opportunity cost & methodology</h3><Evidence value={{ rationale: p.rationale, methodologyVersions: p.methodologyVersions }} /></Panel><Panel title="Marginal allocation trace">{p.marginalAllocation ? p.marginalAllocation.steps.map(s => <article key={s.id}><h3>Step {s.projection.step} · {s.result}</h3><Metrics values={{ "Projected cash": s.projection.context.executableCash, "Preferred candidate": s.preferredDecisionId, "Selected candidate": s.authorizedLot?.decisionId, "Substitution policy": s.substitution?.policy ?? "No substitution", "Authorized quantity": s.authorizedLot?.quantity, "Capital required": s.authorizedLot?.capital, "Stop reason": s.reasons.join(" · ") || "None recorded" }} /><Evidence value={{ assessments: s.assessments.map(a => ({ baseDecisionId: a.baseDecisionId, assessmentId: a.decision.id, decisionState: a.decision.decisionState, executionStatus: a.decision.executionStatus, reasons: a.decision.reasons, requiredReturn: a.decision.requiredReturn, portfolioImpact: a.decision.portfolioImpact, opportunityCost: a.decision.opportunityCost, lineage: a.decision.lineage, evidence: a.decision.input.evidence, assessment: a.decision.input.assessment })), substitution: s.substitution, authorizedLot: s.authorizedLot, supportingEvidence: p.marginalAllocation?.command.frames[s.projection.step]?.substitutionEvidence }} /></article>) : <p>Unavailable — no approved marginal assessment is attached.</p>}</Panel></>;
}
export function ReviewView({ review: r }: { review: ReviewArtifact }) {
  return <><Panel title={`${r.command.type} review`}><Status>{r.status}</Status><p>Review disposition: <strong>{r.disposition}</strong>. Review Outcome ≠ Decision State.</p>{r.disposition === "NO ACTION" && <p>NO ACTION is a normal surveillance outcome.</p>}<Metrics values={{ "Review date": r.command.reviewDate, "Data as-of": r.command.asOf, "Evidence cutoff": r.command.evidenceCutoff, "Snapshot": r.command.snapshotId, "Methodology": r.methodology }} /><p className="notice">A review being due does not require a trade. Annual review does not change policy.</p><Evidence value={{ triggers: r.command.triggers, sections: r.command.sections, theses: r.command.theses, escalation: r.reasons, governance: r.command.governance, linkedEvents: r.linkedEventReviewIds }} /><p>Journal: <Ref route="journal" id={r.id} /></p></Panel>{r.proposal && <ProposalView proposal={r.proposal} />}</>;
}
export function DashboardScreen({ model: m, screen = "dashboard", id, children }: { model: DashboardModel; screen?: string; id?: string; children?: ReactNode }) {
  const d = m.decisions.find(d => d.id === id), r = m.reviews.find(r => r.id === id), card = m.cards.find(c => c.id === id), ranking = id ? m.rankings.find(r => r.id === id) : m.rankings[0];
  const proposal = r?.proposal ?? m.reviews.find(r => r.proposal?.id === id)?.proposal;
  const title = screen === "scoring" ? "Scorecards" : titles[screen] ?? "Unavailable";
  return <div className="app-shell"><aside><Link className="brand" href="/">VN30<span>Value Investing OS</span></Link><nav aria-label="Primary navigation">{navigation.map(g => <div className="nav-group" key={g.group}><p>{g.group}</p>{g.items.map(([key, label]) => <Link key={key} href={`/${key}`} aria-current={key === screen ? "page" : undefined}>{label}</Link>)}</div>)}</nav><p className="local-label">LOCAL FIRST · VND</p></aside><div className="workspace"><header><p>{m.portfolio?.name ?? "Personal investment workspace"}</p><Link href="/data">Data status & integrity</Link></header><main id="main"><p className="eyebrow">{screen === "reviews" && id === "new" ? "Review initiation · server-derived readiness" : screen === "transactions" && id === "new" ? "Accounting fact entry · explicit confirmation" : id && screen !== "holdings" ? "HISTORICAL AS-OF ARTIFACT · READ ONLY" : "CURRENT READ MODEL"}</p><h1>{screen === "dashboard" ? "VN30 Value Investing OS" : title}</h1><div className="trust-strip" role="status"><strong>{m.status === "BLOCKED" ? "BLOCKED — integrity could not be verified" : `Current capital actionability: ${m.current?.actionability ?? "BLOCKED / Unavailable"}`}</strong><span>Portfolio as-of: {m.current?.portfolioAsOf ?? m.state?.asOf ?? "Unavailable"}</span><span>Reconciliation: {m.current?.reconciliation ?? "Unavailable"} · Price freshness: {m.current?.priceFreshness ?? "Unavailable"}</span><span>PASS indicates current input integrity. M6.5/M6.6 still authorize investment actions.</span></div>{(m.current?.scope === "SYNTHETIC_TEST" || m.cards.some(c => c.input.artifactScope === "SYNTHETIC_TEST") || m.decisions.some(d => d.scope === "SYNTHETIC_TEST") || m.reviews.some(r => r.command.scope === "SYNTHETIC_TEST")) && <p className="notice">SYNTHETIC TEST ONLY artifacts are present. They are not production investment evidence.</p>}{m.message && <p role="alert" className="notice">{m.message}</p>}{m.truncated && <p className="notice">Showing up to 100 records per artifact family. Older references may be outside this catalog.</p>}
  {screen === "dashboard" && <><Metrics values={{ "NAV (VND)": m.current?.nav, "Ledger cash (VND)": m.state?.cash, "Invested market value (VND)": m.current?.marketValue, "Unrealized P&L (VND)": m.current?.unrealizedPnl, "Realized P&L (VND)": m.state?.realizedPnl, "Net contributions (VND)": m.state?.netContributions }} />{!m.portfolio && <Panel title="Chưa có dữ liệu đầu tư"><p>Dữ liệu danh mục sẽ xuất hiện khi chức năng quản lý danh mục được thiết lập.</p><p>No portfolio has been initialized. No financial values have been fabricated.</p></Panel>}<Panel title="Attention needed"><p>{m.current?.reasons.join(" · ") || "Current read-model integrity passed. Investment authorization remains with M6.5/M6.6."}</p><Link href="/data">Inspect missing data</Link></Panel><Panel title="Operational summaries"><Metrics values={{ "Latest scoring as-of": m.cards[0]?.asOf, "Latest ranking status": m.rankings[0]?.status, "Latest allocation outcome": m.reviews.find(r => r.proposal)?.proposal?.outcome, "Latest review status": m.reviews[0]?.status, "Sector concentration": null }} /><p><Link href="/holdings">Inspect holdings</Link> · <Link href="/decisions">Latest decisions</Link> · <Link href="/reviews">Review center</Link></p></Panel><Panel title="Current holdings · M6.3 accounting"><Table headers={["Security", "Shares", "Cost basis (VND)", "Average cost"]} rows={(m.state?.positions ?? []).slice(0, 10).map(p => [<Ref key={p.securityId} route="holdings" id={p.securityId} />, p.quantity, p.openCost, p.averageCost])} empty="No holdings recorded yet." /></Panel><Panel title="Latest decisions · historical as-of"><Table headers={["Decision", "Ticker", "Economic Decision State", "Execution Status", "As-of"]} rows={m.decisions.map(d => [<Ref key={d.id} route="decisions" id={d.id} />, d.ticker, d.decisionState, d.executionStatus, d.asOf])} empty="No formal decisions recorded yet." /></Panel><Panel title="Review attention"><Table headers={["Review", "Type", "Status", "Data as-of", "Reasons"]} rows={m.reviews.filter(r => r.status !== "FINAL").map(r => [<Ref key={r.id} route="reviews" id={r.id} />, r.command.type, r.status, r.command.asOf, r.reasons.join(" · ")])} empty="No pending or escalated reviews in the displayed catalog." /></Panel></>}
  {["dashboard", "holdings", "data"].includes(screen) && <Panel title="Market valuation · current read model"><p>Accounting quantities, cost basis, realized P&L and cash remain M6.3 ledger truth. Market valuation is a separate read model. Sector exposure is informational; it does not authorize risk.</p><Table headers={["Security", "Current price", "Price as-of", "Provider", "Retrieved at", "Price status", "Source reference", "Sector at valuation as-of"]} rows={(m.current?.positions ?? []).map(p => [p.securityId, p.currentPrice, p.priceAsOf, p.provider, p.retrievedAt, p.priceStatus, p.sourceReference, p.sector])} /><Table headers={["Sector", "Market value", "Weight (fraction of NAV)"]} rows={(m.current?.sectors ?? []).map(s => [s.sector, s.marketValue, s.weight])} /></Panel>}
  {screen === "holdings" && <><Metrics values={{ "Ledger cash (VND)": m.state?.cash, "Available cash": null, "Reserved / proposed cash": null, "Unallocated cash": null, "Realized P&L": m.state?.realizedPnl, "Receivables": m.state?.receivables, "Payables": m.state?.payables }} /><Panel title="Authoritative holdings"><Table headers={["Security", "Shares", "Cost basis (VND)", "Average cost", "Realized P&L", "Market value", "Unrealized P&L", "Weight", "Decision", "Score (historical)", "Confidence", "Sector (historical)", "Score as-of"]} rows={(m.state?.positions ?? []).filter(p => !id || p.securityId === id).map(p => [<Ref key={p.securityId} route="holdings" id={p.securityId} />, p.quantity, p.openCost, p.averageCost, p.realizedPnl, m.current?.positions.find(v => v.securityId === p.securityId)?.marketValue, m.current?.positions.find(v => v.securityId === p.securityId)?.unrealizedPnl, m.current?.positions.find(v => v.securityId === p.securityId)?.weight, <Ref key={`${p.securityId}-d`} route="decisions" id={m.decisions.find(d => d.securityId === p.securityId)?.id} />, m.cards.find(c => c.securityId === p.securityId)?.totalScore, m.cards.find(c => c.securityId === p.securityId)?.confidence, m.cards.find(c => c.securityId === p.securityId)?.reference.sector, m.cards.find(c => c.securityId === p.securityId)?.asOf])} empty="No holdings recorded yet." /><p>Data as-of: {m.state?.asOf ?? "Unavailable"} · Accounting method: {m.state?.accountingMethod ?? "Unavailable"}</p></Panel></>}
  {screen === "vn30" && <Panel title="VN30 membership evidence"><p className="notice">Membership below is pinned to scorecard as-of dates. A complete current universe query is unavailable. Membership changes do not generate trades.</p><Table headers={["Ticker", "Company", "Sector", "Membership", "As-of", "Scorecard", "Confidence", "Data quality"]} rows={m.cards.filter((c, i, all) => all.findIndex(x => x.securityId === c.securityId) === i).map(c => [c.ticker, c.input.companyName, c.reference.sector, c.reference.membership, c.asOf, <Ref key={c.id} route="scoring" id={c.id} />, c.confidence, c.dataQuality])} /></Panel>}
  {screen === "ranking" && <>{ranking ? <RankingView ranking={ranking} /> : <Panel title="Formal ranking / Top 10"><p>Unavailable — no formal ranking artifact is recorded.</p><p>Top 10 ≠ Buy list.</p></Panel>}<Panel title="Scorecards"><Table headers={["Scorecard", "Security", "100-point score", "Confidence", "As-of"]} rows={m.cards.map(c => [<Ref key={c.id} route="scoring" id={c.id} />, c.ticker, c.totalScore, c.confidence, c.asOf])} /></Panel></>}
  {screen === "scoring" && <Panel title="Formal scorecard">{card ? <><Metrics values={{ "100-point score": card.totalScore, Confidence: card.confidence, "Data quality": card.dataQuality, Validity: card.validity, "Data as-of": card.asOf, "Evidence cutoff": card.input.knownAt, "Methodology version": card.methodology.semanticVersion, "Scope": card.input.artifactScope }} /><h3>Category and subcategory scores</h3><Table headers={["Category", "Points", "Maximum"]} rows={card.categories.map(c => [c.category, c.points, c.max])} /><Table headers={["Subcategory", "Points", "Evidence"]} rows={card.subcategories.map(c => [c.id, c.points, <Evidence key={c.id} value={c} />])} /><Evidence value={{ categories: card.categories, subcategories: card.subcategories, normalization: card.input.normalization, missingEvidence: card.missingEvidence, blockingEvidence: card.blockingEvidence, evidence: card.input.evidence, thesis: card.input.thesis }} /></> : id ? <p>Unavailable — scorecard reference not found in the catalog.</p> : <Table headers={["Scorecard", "Ticker", "100-point score", "Confidence", "Data as-of"]} rows={m.cards.map(c => [<Ref key={c.id} route="scoring" id={c.id} />, c.ticker, c.totalScore, c.confidence, c.asOf])} empty="No formal scorecards recorded yet." />}</Panel>}
  {screen === "decisions" && (id ? d ? <DecisionView decision={d} /> : <Panel title="Decision unavailable"><p>Reference not found in the catalog.</p></Panel> : <Panel title="Formal decisions"><p>Economic Decision State and Execution Status are separate authorities.</p><Table headers={["Decision", "Ticker", "Economic Decision State", "Execution Status", "Review Status", "As-of", "Scope"]} rows={m.decisions.map(d => [<Ref key={d.id} route="decisions" id={d.id} />, d.ticker, <Status key={`${d.id}-s`}>{d.decisionState}</Status>, d.executionStatus, d.reviewStatus, d.asOf, d.scope])} empty="No formal decisions recorded yet." /></Panel>)}
  {screen === "dca" && <>{proposal ? <ProposalView proposal={proposal} /> : <Panel title="Monthly capital allocation"><p>HOLD CASH is a valid successful outcome. Contribution availability is not a deployment target.</p><Table headers={["Proposal", "Review", "Outcome", "Residual cash", "Evidence cutoff"]} rows={m.reviews.filter(r => r.proposal).map(r => [<Ref key={r.id} route="dca" id={r.id} />, <Ref key={`${r.id}-r`} route="reviews" id={r.id} />, r.proposal!.outcome, r.proposal!.unallocatedCash, r.proposal!.evidenceCutoff])} empty="No allocation proposal recorded yet. Holding cash is valid." /></Panel>}<Panel title="Confirmed execution links"><Evidence value={m.executions} /></Panel></>}
  {screen === "reviews" && id !== "new" && (id ? r ? <ReviewView review={r} /> : <Panel title="Review unavailable"><p>Reference not found in the catalog.</p></Panel> : <Panel title="Review center"><p>Weekly · Monthly DCA · Quarterly · Annual · Event-driven</p><p><Link href="/reviews/new">Start Review · preview authoritative readiness</Link></p><p>NO ACTION and HOLD CASH are normal outcomes. Review schedules do not require trading.</p><Table headers={["Review", "Type", "Status", "Disposition", "Allocation outcome", "Data as-of", "Escalation"]} rows={[...m.reviews].sort((a, b) => Number(b.command.type === "EVENT_DRIVEN") - Number(a.command.type === "EVENT_DRIVEN")).map(r => [<Ref key={r.id} route="reviews" id={r.id} />, r.command.type, r.status, r.disposition, r.proposal?.outcome, r.command.asOf, r.reasons.join(" · ")])} empty="No reviews recorded yet." /></Panel>)}
  {screen === "journal" && <Panel title="Investment Journal"><p>Journal text is evidence and reflection; it is not formal decision authority.</p>{id && r ? <><Evidence value={r.journal} /><h3>Behavioral observations</h3>{r.command.behavioral.map((b, i) => <article key={i}><h4>Potential {b.bias} signal</h4><Evidence value={b} /></article>)}<p>Review: <Ref route="reviews" id={r.id} /></p><Evidence value={m.followUps.filter(f => f.command.reviewId === r.id)} /></> : <Table headers={["Entry", "Type", "Review", "Follow-up"]} rows={m.reviews.filter(r => r.journal).map(r => [<Ref key={r.id} route="journal" id={r.id} />, r.journal!.entryType, r.command.type, r.journal!.nextReview])} empty="No approved journal entries recorded yet." />}</Panel>}
  {screen === "transactions" && <Panel title="Immutable transaction history"><p><Link href="/transactions/new">Record an occurred transaction</Link></p><p>Posted facts cannot be edited or deleted. Corrections use explicit reversals.</p>{id && id !== "new" ? <Evidence value={m.transactions.find(t => t.facts.id === id)} /> : id !== "new" && <Table headers={["Transaction", "Type", "Security", "Quantity", "Price", "Fee", "Tax", "Event date", "Reversal / settlement"]} rows={m.transactions.map(t => [<Ref key={t.facts.id} route="transactions" id={t.facts.id} />, t.facts.type, t.facts.securityId, t.facts.quantity, t.facts.price, t.facts.fee, t.facts.tax, t.facts.eventAt, t.facts.reversesId ?? t.facts.settlesId ?? "None"])} empty="No transactions recorded yet." />}{children}</Panel>}
  {screen === "risk" && <Panel title="Risk evidence"><p>Current concentration, sector exposure and drawdown: Unavailable. Risk evidence below is historical as-of; it does not create trade instructions.</p>{m.decisions.map(d => <article key={d.id}><h3><Ref route="decisions" id={d.id} /></h3><Evidence value={{ asOf: d.asOf, risk: d.input.assessment.risk, portfolioImpact: d.portfolioImpact }} /></article>)}</Panel>}
  {screen === "performance" && <Panel title="Portfolio performance"><Metrics values={{ "Realized P&L (VND)": m.state?.realizedPnl, "Net dividends (VND)": m.state?.netDividends, "NAV history": null, "VN30 benchmark comparison": null, "TWR / XIRR / CAGR": null }} /><p>No compatible approved benchmark/time-series query is available. No historical series is fabricated.</p></Panel>}
  {screen === "audit" && <><Panel title="Audit lineage"><p>Portfolio Snapshot → Scorecard → Ranking → Decision → Review → Marginal Assessment → Allocation Proposal → Transaction → Post-decision Review</p><Table headers={["Artifact", "Type", "As-of / recorded at"]} rows={[...m.cards.map(c => [<Ref key={c.id} route="scoring" id={c.id} />, "Scorecard", c.asOf]), ...m.rankings.map(r => [<Ref key={r.id} route="ranking" id={r.id} />, "Ranking", r.asOf]), ...m.decisions.map(d => [<Ref key={d.id} route="decisions" id={d.id} />, "Decision", d.asOf]), ...m.reviews.map(r => [<Ref key={r.id} route="reviews" id={r.id} />, "Review", r.recordedAt])]} />{id && <><h3>Referenced snapshot / marginal assessment</h3><p>Historical pinned evidence for {id}.</p><Evidence value={m.decisions.find(d => d.lineage.snapshotId === id)?.input.portfolio ?? m.reviews.find(r => r.command.snapshotId === id)?.portfolio ?? m.reviews.flatMap(r => r.proposal?.marginalAllocation?.steps ?? []).find(step => step.id === id) ?? null} /></>}<Evidence value={{ executionLinks: m.executions, postDecisionReviews: m.followUps, accountingLineage: m.state && { watermark: m.state.ledgerWatermark, methodologyIds: m.state.methodologyIds, asOf: m.state.asOf } }} /></Panel><Panel title="Methodology registry"><Evidence value={m.methods} /></Panel></>}
  {["data", "settings", "imports"].includes(screen) && <Panel title={screen === "settings" ? "Local configuration" : "Data freshness & integrity"}><p>Local-first SQLite. No cloud account or broker connection is required.</p><Metrics values={{ "Portfolio as-of": m.state?.asOf, "Ledger watermark": m.state?.ledgerWatermark, "Latest score as-of": m.cards[0]?.asOf, "Latest decision as-of": m.decisions[0]?.asOf, "Price freshness": m.current?.priceFreshness, "Reference freshness": m.current?.referenceFreshness, "Reference as-of": m.current?.referenceAsOf, "Evidence cutoff": m.current?.evidenceCutoff, "Source version": m.current?.sourceVersion, "Reference version": m.current?.referenceVersion, "Valuation methodology": m.current?.valuationMethodology, "Fundamental freshness": null, Reconciliation: m.current?.reconciliation }} /><p className="notice">Current read-model status: {m.current?.status ?? "Unavailable"}. {m.current?.reasons.join(" · ")} Persisted analytical artifacts remain historical as-calculated outputs.</p><p>Refresh through the approved local data/application workflow. Import UI and methodology editing are unavailable until their approved commands exist.</p><Link href="/audit">Inspect methodology and lineage</Link></Panel>}
  {screen === "reviews" && children}
  </main><footer>M6.7 · Evidence before action · Proposal and transaction remain distinct</footer></div></div>;
}
