import Link from 'next/link';
import type {ReactNode} from 'react';
import type {DataFreshnessModel,PublicFinancialFact} from '@/domain/fundamentals/freshness';
function Fields({values}:{values:Record<string,ReactNode>}){return <dl className="evidence">{Object.entries(values).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??'UNKNOWN / Unavailable'}</dd></div>)}</dl>;}
function Rows({headers,rows}:{headers:readonly string[];rows:readonly ReactNode[][]}){return <div className="table-scroll" role="region" aria-label={headers.join(', ')} tabIndex={0}><table><thead><tr>{headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v??'Unavailable'}</td>)}</tr>)}</tbody></table></div>;}
function Fact({fact:f,model:m}:{fact:PublicFinancialFact;model:DataFreshnessModel}){
 const link=(id:string)=>m.facts.some(f=>f.id===id)?<a href={`#fact-${id}`}>{id}</a>:<span>{id} · ancestor verified; outside pinned display</span>;
 return <details id={`fact-${f.id}`} className="financial-fact"><summary>{f.ticker} · {f.itemId} · {f.periodEnd} · {f.selected?'SELECTED':'EXCLUDED'} · {f.publication.publicationPrecision}</summary>
  <Fields values={{'Observation ID':f.id,'Reporting scope':f.reportingScope,'Reporting period':`${f.periodStart} → ${f.periodEnd}`,'Normalized value':f.value,'Unit / currency':`${f.unit} / ${f.currency??'none'}`,'Quality / applicability':`${f.quality} / ${f.applicability}`,'Publication status':f.publication.publicationStatus,'Publication precision':f.publication.publicationPrecision,'Exact issuer publishedAt':f.publication.publishedAt,'Publication date (date-only)':f.publication.publicationDate,'Publication timezone':f.publication.timezone,'Publication evidence':f.publicationEvidence.url?<a href={f.publicationEvidence.url} target="_blank" rel="noreferrer">Open public disclosure</a>:f.publicationEvidence.recorded?'Recorded; internal reference withheld':'UNKNOWN', 'Provider receivedAt':f.providerReceivedAt,'Local retrievedAt':f.retrievedAt,'Local ingestedAt':f.ingestedAt,'Availability status':f.availability.status,'Operational availableAt':f.availability.availableAt,'Public policy boundary (not issuer publication)':f.availability.publicBoundary,'Conservative DATE_ONLY fallback':f.availability.publicFallbackBoundary,'Trusted public receipt boundary':f.availability.evidenceBackedBoundary,'Boundary evidence class':f.availability.boundaryBasis,'Receipt proof knownAt':f.availability.receiptKnownAt,'Availability assessment':f.availability.assessmentId,'Availability policy':f.availability.policyVersion,'Policy hash':f.availability.policyHash,'Availability finding':f.availability.finding??'None','Provider':f.source.provider,'Source version':f.source.versionId,'Adapter / schema':`${f.source.adapterVersion} / ${f.source.schemaVersion}`,'Raw capture ID':f.source.captureId,'Raw payload hash':f.source.payloadHash,'Public source document':f.source.documentUrl?<a href={f.source.documentUrl} target="_blank" rel="noreferrer">Open source document</a>:'Public link unavailable','Revision kind':f.revision.kind,'Correction knownAt':f.revision.correctionKnownAt,'Predecessor':f.revision.predecessorId?link(f.revision.predecessorId):'None','Revision chain':f.revision.chain.length?<ul>{f.revision.chain.map(id=><li key={id}>{link(id)}</li>)}</ul>:'Original observation'}} />
  {f.publication.publicationPrecision==='DATE_ONLY'&&<p className="notice">DATE_ONLY remains date-only. Policy and receipt boundaries do not establish an exact issuer publication time.</p>}
 </details>;
}
export function DataFreshnessView({model:m}:{model:DataFreshnessModel}){
 const s=m.snapshot,c=m.counts;
 return <>
  <section aria-label="Financial data coverage"><h2>Financial data coverage</h2><p>Sealed snapshot coverage and independently reviewed scoring inputs. Data readiness does not authorize an investment action.</p>
   <p role="status">Snapshot integrity: {m.status} · DI readiness review: {m.review.status}</p>
   {m.status==='EMPTY'&&<p>No sealed fundamental snapshot. Universe size and readiness are unknown.</p>}
   {m.status==='BLOCKED'&&<p role="alert">Snapshot integrity or external governance could not be verified. Coverage and readiness are unavailable.</p>}
   <dl className="metrics">{Object.entries({'Pinned universe':c.universe,'Securities with all required facts':c.coveredSecurities,'Selected canonical facts':c.selectedFacts,'Data-ready at snapshot cutoff':c.dataReady,'Score-ready at snapshot cutoff':c.scoringReady}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v??'UNKNOWN / Unavailable'}</dd></div>)}</dl>
   {s&&<><p className="notice">Historical snapshot · READ ONLY. Readiness applies to the pinned cutoffs, not current freshness or trade actionability.</p>{s.scope==='SYNTHETIC_TEST'&&<p className="notice">SYNTHETIC TEST ONLY — not production financial evidence.</p>}{s.mode==='AS_REVISED'&&<p className="notice">AS_REVISED · diagnostic only; cannot authorize FORMAL scoring.</p>}{s.builtAt>m.viewedAt&&<p className="notice">Snapshot build is later than this view clock. Do not interpret it as currently known information.</p>}
   <Fields values={{'Snapshot run':s.runId,'Content hash':s.contentHash,'Scope / mode':`${s.scope} / ${s.mode}`,'Built at':s.builtAt,'Decision as-of':s.decisionAsOf,'System knowledge cutoff':s.systemKnownAt,'Fundamental cutoff':s.fundamentalCutoff,'Market cutoff':s.marketCutoff,'Universe version':s.universeVersion,'Universe known at':s.universeKnownAt,'Requirements version':s.requirementsVersion,'Viewed at':m.viewedAt}} />
   {s.blockers.length>0&&<><h3>Snapshot blockers</h3><ul>{s.blockers.map(b=><li key={b}>{b}</li>)}</ul></>}
   <h3>Independent review selection</h3>{m.acceptanceChoices.length?<ul>{m.acceptanceChoices.map(a=><li key={a.id}><Link href={`/data/${encodeURIComponent(s.runId)}?acceptance=${encodeURIComponent(a.id)}`}>{a.id}</Link> · {a.acceptedAt} · stored reference, verification required</li>)}</ul>:<p>No independent DI acceptance recorded for this run.</p>}
   <Fields values={{'Selected DI acceptance':m.review.acceptanceId,'Review status':m.review.status,'Accepted at':m.review.acceptedAt,'Readiness algorithm':m.review.algorithm}} />
   {m.review.status!=='VERIFIED'&&<p className="notice">BLOCKED scoring readiness — select an acceptance for this exact run and supply independently verified server authority. Stored PASS declarations alone do not establish readiness.</p>}
   {m.review.algorithm==='strict-canonical-m3-readiness-v1'&&<p className="notice">Legacy v1 historical replay. Its narrower dataReady definition is withheld here; new FORMAL scoring requires reviewed v2 inputs.</p>}
   </>}
  </section>
  {m.catalog.length>0&&<section aria-label="Snapshot runs"><h2>Snapshot runs</h2><p>Build time does not establish current data freshness. Each link selects its exact immutable run.</p><ul>{m.catalog.map(r=><li key={r.runId}><Link href={`/data/${encodeURIComponent(r.runId)}`}>{r.runId}</Link> · {r.builtAt}</li>)}</ul>{m.catalogTruncated&&<p>Showing the latest 50 catalog references. An older exact run remains addressable by its ID.</p>}</section>}
  {s&&<section aria-label="Universe coverage and readiness"><h2>Universe coverage and readiness</h2><p>{c.coveredSecurities} / {c.universe} securities have every required fact selected at the snapshot cutoff.</p>
   <Rows headers={['Security','Sector','Fundamental coverage','Market','Fundamentals','Valuation','Confidence','Assessments / gates','Data-ready','Score-ready','Blockers']} rows={m.securities.map(v=>[<a key={v.securityId} href={`#security-${v.securityId}`}>{v.ticker}</a>,v.sector,v.covered?'COVERED':'BLOCKED / MISSING',v.readiness?.market,v.readiness?.fundamentals,v.readiness?.valuation,v.readiness?.confidence,v.readiness?.assessmentsAndGates,m.review.algorithm==='strict-canonical-m3-readiness-v2'&&v.readiness?String(v.readiness.dataReady):'UNKNOWN',v.readiness?String(v.readiness.readyForScoring):'UNKNOWN',v.readiness?v.readiness.blockers.join(' · ')||'None':!v.covered?'Required facts missing':'Readiness review unavailable'])} />
   <p>Age at view time uses the snapshot&apos;s pinned thresholds for diagnosis only. It never refreshes historical DI acceptance.</p>
   {m.securities.map(v=><details id={`security-${v.securityId}`} key={v.securityId}><summary>{v.ticker} · requirements and freshness</summary><Rows headers={['Item','Scope','Period','Maximum age (days)','Selected observations','Coverage finding','At cutoff','Age at view (days)','At view — diagnostic']} rows={v.requirements.map(q=>[q.itemId,q.reportingScope,`${q.periodStart} → ${q.periodEnd}`,q.maxAgeDays,q.selectedIds.length?q.selectedIds.map(id=><a key={id} href={`#fact-${id}`}>{id}</a>):'MISSING / BLOCKED',q.finding??'None',q.freshnessAtCutoff,q.ageDaysAtView,q.freshnessAtView])} /></details>)}
  </section>}
  {m.facts.length>0&&<section aria-label="Financial provenance"><h2>Financial provenance</h2><p>Public disclosure, provider receipt and local retrieval/ingestion remain separate clocks. Raw payloads and private references are withheld.</p>{m.facts.map(f=><Fact key={f.id} fact={f} model={m} />)}</section>}
  {m.derived.length>0&&<section aria-label="Derived metric lineage"><h2>Derived metric lineage</h2>{m.derived.map(d=><details key={d.id}><summary>{d.metric} · {d.id} · {d.selected?'SELECTED':'EXCLUDED'}</summary><Fields values={{'Result':d.value,'Unit':d.unit,'Status':d.status,'Confidence':d.confidence,'Crosswalk version':d.crosswalkVersion}} /><Rows headers={['Role','Operation','Operand value','Canonical constituents','Adjustment review knownAt']} rows={d.operands.map(o=>[o.role,o.operation,o.value,o.observationIds.map(id=><a key={id} href={`#fact-${id}`}>{id}</a>),o.reviewKnownAt])} /></details>)}</section>}
 </>;
}
