// @vitest-environment node
import {it,expect} from 'vitest';
import {snapshotDerivationFixture} from '../fixtures/snapshot';
import {release} from '../fixtures/fundamentals';
import {deriveFundamentals} from '@/domain/fundamentals/derivation';
import {loadDerivationCrosswalk} from '@/infrastructure/fundamentals/derivation-crosswalk';
import {normalizationHash} from '@/infrastructure/fundamentals/reviewed-statement';
import {assessAvailability} from '@/domain/fundamentals/availability';
import {buildFundamentalSnapshot} from '@/domain/fundamentals/snapshot';
import {snapshotHash} from '@/infrastructure/fundamentals/snapshot-hash';
import {bridgeScoringInputs} from '@/domain/fundamentals/scoring-bridge';
function fixture(mixed=false){const original=snapshotDerivationFixture(),observations=original.observations.map((o,i)=>mixed&&i===1?{...o,publication:{publishedAt:null,publicationDate:'2026-07-25',publicationPrecision:'DATE_ONLY' as const,publicationStatus:'VERIFIED' as const,timezone:'UTC',evidenceReference:'synthetic-derived-date-only'}}:o),policy=mixed?{...original.policy,governanceStatus:'APPROVED' as const,approvalReference:'synthetic-date-only-policy',algorithm:'operational-evidence-v2' as const,dateOnlyEvidenceClasses:[]}:original.policy,f={...original,observations,policy,request:{...original.request,policy}},c=loadDerivationCrosswalk(release),crosswalk={...c.crosswalk,registryHash:f.registry.registryHash,recordedAt:f.policy.recordedAt,effectiveDate:'2026-01-01'},request={id:f.request.derivedIds[0],scope:f.request.scope,securityId:f.observation.securityId,sector:f.observation.sector,metric:'FCF' as const,periodStart:f.observation.periodStart,periodEnd:f.observation.periodEnd,cyclical:false,operands:f.observations.map(o=>({id:'operand-'+o.id,operation:'REPORTED' as const,observationIds:[o.id],adjustment:null}))},derived=deriveFundamentals({request,recordedAt:f.request.builtAt,registry:f.registry,crosswalk,crosswalkHash:normalizationHash(crosswalk),observations:f.observations,hash:normalizationHash}),assessments=f.observations.map(o=>assessAvailability({id:'assessment-'+o.id,observation:o,registry:f.registry,policy:f.policy,assessedAt:f.assessment.assessedAt,hash:snapshotHash})),sources={registry:f.registry,observations:f.observations,assessments,derived:[derived]},snapshot=buildFundamentalSnapshot(f.request,sources,snapshotHash),plan={facts:[],external:[],metrics:[{derivationId:derived.id,requestId:'bridged-fcf',evidenceIds:['bridged-CFO','bridged-capex'] as const,validThrough:f.request.decisionAsOf}]};return {...f,derived,sources,snapshot,plan};}
it('strict bridge preserves ordered governed CFO/capex values, window and FCF request without accepting a vendor ratio',()=>{const f=fixture(),g=bridgeScoringInputs(f.snapshot,f.observation.securityId,f.plan,f.sources);expect(g.evidence.map(e=>e.value)).toEqual(['100','30']);expect(g.evidence.map(e=>e.family)).toEqual(['canonical-CFO','canonical-CAPEX']);expect(g.metrics[0]).toMatchObject({metric:'FCF',evidenceRefs:['bridged-CFO','bridged-capex'],comparable:true,normalization:{kind:'AS_REPORTED'}});expect(g.evidence.every(e=>e.receivedAt===f.assessment.availableAt&&e.periodStart===f.derived.request.periodStart)).toBe(true);});
it('a forged derived result, unavailable constituent or unselected derived artifact fails closed',()=>{const f=fixture();expect(()=>bridgeScoringInputs(f.snapshot,f.observation.securityId,f.plan,{...f.sources,derived:[{...f.derived,value:'999'}]})).toThrow();expect(()=>bridgeScoringInputs({...f.snapshot,derivedIds:[]},f.observation.securityId,f.plan,f.sources)).toThrow();expect(()=>bridgeScoringInputs({...f.snapshot,members:f.snapshot.members.slice(1)},f.observation.securityId,f.plan,f.sources)).toThrow();});
it('DATE_ONLY constituents and later review knowledge cannot manufacture exact publication or historical metric eligibility',()=>{const f=fixture(),observations=f.observations.map(o=>({...o,publication:{publishedAt:null,publicationDate:'2026-07-25',publicationPrecision:'DATE_ONLY' as const,publicationStatus:'VERIFIED' as const,timezone:'UTC',evidenceReference:'synthetic-date-only'}}));expect(()=>bridgeScoringInputs(f.snapshot,f.observation.securityId,f.plan,{...f.sources,observations})).toThrow();expect(()=>bridgeScoringInputs(f.snapshot,f.observation.securityId,f.plan,{...f.sources,derived:[{...f.derived,crosswalk:{...f.derived.crosswalk,recordedAt:'2026-07-29T00:00:00.000Z'}}]})).toThrow();});

it('mixed DATE_ONLY/TIMESTAMP derived operands replay FCF unchanged without a fake composite clock and use the latest knowledge boundary',()=>{
 const f=fixture(true),g=bridgeScoringInputs(f.snapshot,f.observation.securityId,f.plan,f.sources);
 expect(f.derived.value).toBe('70');expect(g.evidence.map(e=>e.value)).toEqual(['100','30']);expect(g.evidence[0].publishedAt).toBe(f.observations[0].publication.publishedAt);expect(g.evidence[1].publishedAt).toBeNull();expect(g.evidence[1].time!.constituents[0].publicationPrecision).toBe('DATE_ONLY');
 for(const e of g.evidence)expect(e.receivedAt).toBe([...e.time!.constituents.map(c=>c.availableAt),...e.time!.reviewKnownAt].sort().at(-1));
 const crosswalk={...f.derived.crosswalk,recordedAt:'2026-07-26T23:59:00.000Z'},later=bridgeScoringInputs(f.snapshot,f.observation.securityId,f.plan,{...f.sources,derived:[{...f.derived,crosswalk}]});expect(later.evidence.every(e=>e.receivedAt===crosswalk.recordedAt)).toBe(true);expect(later.evidence[1].publishedAt).toBeNull();
});
it('a quarter-from-YTD composite keeps both publication constituents and null publishedAt when either is DATE_ONLY',()=>{
 const f=snapshotDerivationFixture(),policy={...f.policy,algorithm:'operational-evidence-v2' as const,dateOnlyEvidenceClasses:[],governanceStatus:'APPROVED' as const,approvalReference:'synthetic-YTD-availability'},observations=f.observations.flatMap((o,j)=>[0,1].map(i=>({...o,id:'composite-'+j+'-'+i,periodStart:'2026-01-01',periodEnd:i?'2026-06-30':'2026-03-31',periodType:'YTD' as const,fiscalQuarter:(i+1) as 1|2,normalized:{...o.normalized,value:j?(i?'9':'5'):(i?'50':'20')},publication:i?{publishedAt:null,publicationDate:'2026-07-25',publicationPrecision:'DATE_ONLY' as const,publicationStatus:'VERIFIED' as const,timezone:'UTC',evidenceReference:'synthetic-YTD-date-only'}:o.publication}))),c=loadDerivationCrosswalk(release),crosswalk={...c.crosswalk,registryHash:f.registry.registryHash,recordedAt:f.policy.recordedAt,effectiveDate:'2026-01-01',routes:[{sector:f.observation.sector,metric:'FCF' as const,operands:[{role:'CFO',itemId:'CFO',operation:'QUARTER_FROM_YTD' as const},{role:'issuer_capex',itemId:'CAPEX',operation:'QUARTER_FROM_YTD' as const}]}]},request={id:'composite-FCF',scope:f.request.scope,securityId:f.observation.securityId,sector:f.observation.sector,metric:'FCF' as const,periodStart:'2026-04-01',periodEnd:'2026-06-30',cyclical:false,operands:[0,1].map(j=>({id:'composite-operand-'+j,operation:'QUARTER_FROM_YTD' as const,observationIds:observations.slice(j*2,j*2+2).map(o=>o.id),adjustment:null}))},derived=deriveFundamentals({request,recordedAt:f.request.builtAt,registry:f.registry,crosswalk,crosswalkHash:normalizationHash(crosswalk),observations,hash:normalizationHash}),assessments=observations.map(o=>assessAvailability({id:'assessment-'+o.id,observation:o,registry:f.registry,policy,assessedAt:f.assessment.assessedAt,hash:snapshotHash})),sources={registry:f.registry,observations,assessments,derived:[derived]},snapshotRequest={...f.request,policy,derivedIds:[derived.id],requirements:observations.map(o=>({...f.request.requirements[0],itemId:o.itemId,periodStart:o.periodStart,periodEnd:o.periodEnd})),assessmentPins:assessments.map(a=>({observationId:a.observationId,assessmentId:a.id}))},snapshot=buildFundamentalSnapshot(snapshotRequest,sources,snapshotHash),g=bridgeScoringInputs(snapshot,f.observation.securityId,{facts:[],external:[],metrics:[{derivationId:derived.id,requestId:'composite-FCF-request',evidenceIds:['composite-CFO','composite-CAPEX'],validThrough:f.request.decisionAsOf}]},sources);
 expect(derived.value).toBe('26');expect(g.evidence.map(e=>e.value)).toEqual(['30','4']);for(const e of g.evidence){expect(e.publishedAt).toBeNull();expect(e.time!.constituents.map(c=>c.publicationPrecision)).toEqual(['TIMESTAMP','DATE_ONLY']);expect(e.time!.constituents.map(c=>c.evidenceReference)).toEqual([observations[0].publication.evidenceReference,'synthetic-YTD-date-only']);expect(e.receivedAt).toBe([...e.time!.constituents.map(c=>c.availableAt),...e.time!.reviewKnownAt].sort().at(-1));}
});
