// @vitest-environment node
import {it,expect} from 'vitest';
import {snapshotDerivationFixture} from '../fixtures/snapshot';
import {release} from '../fixtures/fundamentals';
import {deriveFundamentals} from '@/domain/fundamentals/derivation';
import {loadDerivationCrosswalk} from '@/infrastructure/fundamentals/derivation-crosswalk';
import {normalizationHash} from '@/infrastructure/fundamentals/reviewed-statement';
import {assessAvailability} from '@/domain/fundamentals/availability';
import {buildFundamentalSnapshot} from '@/domain/fundamentals/snapshot';
import {snapshotHash} from '@/infrastructure/fundamentals/snapshot-hash';
import {bridgeScoringInputs} from '@/domain/fundamentals/scoring-bridge';
function fixture(){const f=snapshotDerivationFixture(),c=loadDerivationCrosswalk(release),crosswalk={...c.crosswalk,registryHash:f.registry.registryHash,recordedAt:f.policy.recordedAt,effectiveDate:'2026-01-01'},request={id:f.request.derivedIds[0],scope:f.request.scope,securityId:f.observation.securityId,sector:f.observation.sector,metric:'FCF' as const,periodStart:f.observation.periodStart,periodEnd:f.observation.periodEnd,cyclical:false,operands:f.observations.map(o=>({id:'operand-'+o.id,operation:'REPORTED' as const,observationIds:[o.id],adjustment:null}))},derived=deriveFundamentals({request,recordedAt:f.request.builtAt,registry:f.registry,crosswalk,crosswalkHash:normalizationHash(crosswalk),observations:f.observations,hash:normalizationHash}),assessments=f.observations.map(o=>assessAvailability({id:'assessment-'+o.id,observation:o,registry:f.registry,policy:f.policy,assessedAt:f.assessment.assessedAt,hash:snapshotHash})),sources={registry:f.registry,observations:f.observations,assessments,derived:[derived]},snapshot=buildFundamentalSnapshot(f.request,sources,snapshotHash),plan={facts:[],external:[],metrics:[{derivationId:derived.id,requestId:'bridged-fcf',evidenceIds:['bridged-CFO','bridged-capex'] as const,validThrough:f.request.decisionAsOf}]};return {...f,derived,sources,snapshot,plan};}
it('strict bridge preserves ordered governed CFO/capex values, window and FCF request without accepting a vendor ratio',()=>{const f=fixture(),g=bridgeScoringInputs(f.snapshot,f.observation.securityId,f.plan,f.sources);expect(g.evidence.map(e=>e.value)).toEqual(['100','30']);expect(g.evidence.map(e=>e.family)).toEqual(['canonical-CFO','canonical-CAPEX']);expect(g.metrics[0]).toMatchObject({metric:'FCF',evidenceRefs:['bridged-CFO','bridged-capex'],comparable:true,normalization:{kind:'AS_REPORTED'}});expect(g.evidence.every(e=>e.receivedAt===f.assessment.availableAt&&e.periodStart===f.derived.request.periodStart)).toBe(true);});
it('a forged derived result, unavailable constituent or unselected derived artifact fails closed',()=>{const f=fixture();expect(()=>bridgeScoringInputs(f.snapshot,f.observation.securityId,f.plan,{...f.sources,derived:[{...f.derived,value:'999'}]})).toThrow();expect(()=>bridgeScoringInputs({...f.snapshot,derivedIds:[]},f.observation.securityId,f.plan,f.sources)).toThrow();expect(()=>bridgeScoringInputs({...f.snapshot,members:f.snapshot.members.slice(1)},f.observation.securityId,f.plan,f.sources)).toThrow();});
it('DATE_ONLY constituents and later review knowledge cannot manufacture exact publication or historical metric eligibility',()=>{const f=fixture(),observations=f.observations.map(o=>({...o,publication:{publishedAt:null,publicationDate:'2026-07-25',publicationPrecision:'DATE_ONLY' as const,publicationStatus:'VERIFIED' as const,timezone:'UTC',evidenceReference:'synthetic-date-only'}}));expect(()=>bridgeScoringInputs(f.snapshot,f.observation.securityId,f.plan,{...f.sources,observations})).toThrow();expect(()=>bridgeScoringInputs(f.snapshot,f.observation.securityId,f.plan,{...f.sources,derived:[{...f.derived,crosswalk:{...f.derived.crosswalk,recordedAt:'2026-07-29T00:00:00.000Z'}}]})).toThrow();});
